language: racket

notifications:
  irc: "chat.freenode.net#Heather"
  email: false

env:
 - RACKET_VERSION=5.3.5

before_install:
 - curl -L https://github.com/greghendershott/travis-racket/releases/v0.1/1886/install-racket.sh | sh
 - sudo apt-get update

install:

before_script:

script:
 - /usr/racket/bin/raco make -v Serene.rkt
 - /usr/racket/bin/raco make -v ss.rkt
